# Generated by Django 2.0 on 2020-04-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=8, unique=True, verbose_name='昵称')),
                ('address', models.IntegerField(default=0, verbose_name='国家')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(max_length=100, verbose_name='头像')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
